### PR TITLE
Import scene entities from Dirigera

### PR DESCRIPTION
**Pull request by bjorncs**
This adds Dirigera scenes into HA with an activate action that triggers the scene.
Import of wake up scenes will fail until https://github.com/Leggin/dirigera/pull/71 is released.

### CODE REVIEW

**Comment by sanjoyg** [comment]
Should I merge this?

**Comment by bjorncs** [comment]
It's ready :shipit:! Wake-up scenes is [a rather new feature](https://www.reddit.com/r/tradfri/comments/1b7tqxs/good_morning_from_%C3%A4lmhult_we_hope_you_had_a_great/) and adoption is likely low. I doubt this is going to be a big issue.

**Comment by sanjoyg** [comment]
@slajob you have merge permissions so you could merge as well

@bjorncs will you updated the README as well to indicate the scene addition, I dont understand is as much

**Comment by bjorncs** [comment]
@sanjoyg https://github.com/sanjoyg/dirigera_platform/pull/41

**Pull request merged**
